import SwiftUI

struct AISettingsSection: View {
    @StateObject private var settings = SettingsManager.shared
    @Environment(\.colorScheme) var colorScheme
    @State private var showAPIKey = false

    var body: some View {
        VStack(spacing: 0) {
            // Master toggle
            SettingsToggleRow(
                title: "Enable AI Features",
                subtitle: "Journal prompts, word study summaries, and Smart Search powered by Google Gemini",
                isOn: $settings.aiEnabled
            )

            if settings.aiEnabled {
                SettingsDivider()

                // API Key entry
                VStack(alignment: .leading, spacing: 10) {
                    HStack {
                        Text("Gemini API Key")
                            .font(.subheadline)
                            .fontWeight(.medium)
                            .foregroundStyle(Color.adaptiveText(colorScheme))

                        Spacer()

                        Button {
                            showAPIKey.toggle()
                        } label: {
                            Image(systemName: showAPIKey ? "eye.slash" : "eye")
                                .font(.caption)
                                .foregroundStyle(Color.adaptiveTextSecondary(colorScheme))
                        }
                    }

                    Group {
                        if showAPIKey {
                            TextField("Enter API key", text: $settings.geminiAPIKey)
                        } else {
                            SecureField("Enter API key", text: $settings.geminiAPIKey)
                        }
                    }
                    .font(.subheadline)
                    .autocorrectionDisabled()
                    .textInputAutocapitalization(.never)
                    .padding(12)
                    .background(Color.adaptiveBackground(colorScheme))
                    .clipShape(RoundedRectangle(cornerRadius: 10))
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .stroke(Color.adaptiveBorder(colorScheme), lineWidth: 1)
                    )

                    Text("Your API key is stored only on this device and never shared. Get a free key at aistudio.google.com.")
                        .font(.caption)
                        .foregroundStyle(Color.adaptiveTextSecondary(colorScheme))
                        .lineSpacing(3)

                    if !settings.geminiAPIKey.isEmpty {
                        HStack(spacing: 4) {
                            Image(systemName: "checkmark.circle.fill")
                                .foregroundStyle(Color.green)
                            Text("API key saved")
                                .foregroundStyle(Color.green)
                        }
                        .font(.caption)
                    }
                }
                .padding(.vertical, 12)

                SettingsDivider()

                // Feature overview
                VStack(alignment: .leading, spacing: 12) {
                    Text("What AI Powers")
                        .font(.caption)
                        .fontWeight(.semibold)
                        .foregroundStyle(Color.adaptiveTextSecondary(colorScheme))

                    featureRow(
                        icon: "book.closed.fill",
                        title: "Verse Journal Prompts",
                        description: "Tap 'Journal' on any selected verse to get 6 AI-generated reflection prompts specific to that passage."
                    )

                    Divider()

                    featureRow(
                        icon: "character.book.closed.fill",
                        title: "Word Study Summary",
                        description: "A concise AI summary appears at the top of every word study card, synthesizing the word's meaning and theological significance."
                    )

                    Divider()

                    featureRow(
                        icon: "sparkles",
                        title: "Smart Search",
                        description: "Switch to Smart mode in the search panel and ask natural-language questions like 'verses about forgiveness' or 'the Greek word for love'."
                    )
                }
                .padding(.vertical, 12)

                SettingsDivider()

                Text("AI responses are generated by Gemini and may be imperfect. Always verify insights with Scripture.")
                    .font(.caption)
                    .foregroundStyle(Color.adaptiveTextSecondary(colorScheme))
                    .lineSpacing(3)
                    .padding(.vertical, 8)
            }
        }
    }

    private func featureRow(icon: String, title: String, description: String) -> some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: icon)
                .font(.caption)
                .foregroundStyle(Color.reforgedGold)
                .frame(width: 16)
                .padding(.top, 2)

            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .font(.caption)
                    .fontWeight(.semibold)
                    .foregroundStyle(Color.adaptiveText(colorScheme))

                Text(description)
                    .font(.caption)
                    .foregroundStyle(Color.adaptiveTextSecondary(colorScheme))
                    .lineSpacing(2)
            }
        }
    }
}
