import Foundation
import UserNotifications
import UIKit

class NotificationManager: NSObject, ObservableObject {
    static let shared = NotificationManager()
    
    @Published var deviceToken: String?
    @Published var isAuthorized: Bool = false
    
    private override init() {
        super.init()
    }
    
    /// Request permission to send notifications
    func requestAuthorization() {
        UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .badge, .sound]) { granted, error in
            DispatchQueue.main.async {
                self.isAuthorized = granted
                
                if granted {
                    self.registerForRemoteNotifications()
                }
                
                if let error = error {
                    debugLog("Notification authorization error: \(error.localizedDescription)")
                }
            }
        }
    }
    
    /// Register for remote push notifications
    func registerForRemoteNotifications() {
        DispatchQueue.main.async {
            UIApplication.shared.registerForRemoteNotifications()
        }
    }
    
    /// Check current authorization status
    func checkAuthorizationStatus() {
        UNUserNotificationCenter.current().getNotificationSettings { settings in
            DispatchQueue.main.async {
                self.isAuthorized = settings.authorizationStatus == .authorized
            }
        }
    }
    
    /// Handle successful device token registration
    func handleDeviceToken(_ deviceToken: Data) {
        let token = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
        self.deviceToken = token
        debugLog("Device Token: \(token)")
        
        // TODO: Send this token to your server for push notifications
        // Example: sendTokenToServer(token)
    }
    
    /// Handle registration failure
    func handleRegistrationError(_ error: Error) {
        debugLog("Failed to register for remote notifications: \(error.localizedDescription)")
    }
    
    // MARK: - Daily Reminders
    //
    // Canonical model: each notification *type* (reading, memory review, lesson)
    // produces at most ONE notification per selected weekday, fired at the user's
    // reminder time and staggered a few minutes apart so they never arrive as a
    // barrage. Every type is strictly gated by its own settings toggle AND the
    // master `notificationsEnabled` switch — turning a toggle off removes that type.
    //
    // `scheduleDailyReminder()` is the single source of truth. It tears down every
    // managed request and rebuilds from current settings, so it is safe to call on
    // any settings change or app foreground without ever stacking duplicates.

    /// All notification identifiers this manager may have scheduled. Tearing these
    /// down before every rebuild guarantees we never accumulate duplicate reminders.
    /// Includes legacy IDs (`daily-reading-reminder`, `daily-review-reminder`) so
    /// reminders scheduled by older app versions get cleaned up too.
    private var allManagedIdentifiers: [String] {
        var ids: [String] = ["daily-reading-reminder", "daily-review-reminder", "partner-report-reminder"]
        for weekday in 1...7 {
            ids.append("reading-reminder-\(weekday)")
            ids.append("review-reminder-\(weekday)")
            ids.append("lesson-reminder-\(weekday)")
        }
        return ids
    }

    // Cached personalized reading-reminder content (generated by Gemini once per day).
    private let personalizedLastDateKey = "notification_personalized_last_date"
    private let personalizedTitleKey = "notification_personalized_title"
    private let personalizedBodyKey = "notification_personalized_body"

    /// The reading-reminder content to schedule today: Gemini-personalized copy when
    /// it was generated today and AI is enabled, otherwise the static fallback.
    @MainActor private func currentReadingReminderContent() -> (title: String, body: String) {
        let fallback = ("Time to Read", "Open up to read a chapter and grow in God's Word today.")
        guard SettingsManager.shared.aiEnabled else { return fallback }
        let defaults = UserDefaults.standard
        guard let lastDate = defaults.object(forKey: personalizedLastDateKey) as? Date,
              Calendar.current.isDateInToday(lastDate),
              let title = defaults.string(forKey: personalizedTitleKey),
              let body = defaults.string(forKey: personalizedBodyKey) else {
            return fallback
        }
        return (title, body)
    }

    /// Schedules one weekly-repeating notification per selected weekday under
    /// `"<prefix>-<weekday>"` identifiers, all sharing the given content.
    /// An empty `days` set is treated as every day.
    private func scheduleWeekdaySlots(
        prefix: String,
        days: Set<Int>,
        base: DateComponents,
        title: String,
        body: String,
        action: String,
        center: UNUserNotificationCenter
    ) {
        let resolvedDays = days.isEmpty ? Set(1...7) : days
        let content = UNMutableNotificationContent()
        content.title = title
        content.body = body
        content.sound = .default
        content.userInfo = ["action": action]

        for weekday in resolvedDays.sorted() {
            var components = base
            components.weekday = weekday
            let trigger = UNCalendarNotificationTrigger(dateMatching: components, repeats: true)
            let request = UNNotificationRequest(
                identifier: "\(prefix)-\(weekday)",
                content: content,
                trigger: trigger
            )
            center.add(request)
        }
    }

    /// Returns `base` shifted forward by `minutes`, carrying into the hour as needed.
    private static func offset(_ base: DateComponents, byMinutes minutes: Int) -> DateComponents {
        var result = base
        let total = (base.minute ?? 0) + minutes
        result.minute = total % 60
        result.hour = ((base.hour ?? 0) + total / 60) % 24
        return result
    }

    /// Rebuilds every daily reminder from current settings. Single source of truth —
    /// always removes all managed requests first so reminders never stack up.
    @MainActor func scheduleDailyReminder() {
        let center = UNUserNotificationCenter.current()
        center.removePendingNotificationRequests(withIdentifiers: allManagedIdentifiers)

        let settings = SettingsManager.shared
        guard settings.notificationsEnabled else { return }

        let base = Calendar.current.dateComponents([.hour, .minute], from: settings.dailyReminderTime)

        // Reading reminder — at the reminder time.
        if settings.readingPlanReminders {
            let (title, body) = currentReadingReminderContent()
            scheduleWeekdaySlots(prefix: "reading-reminder", days: settings.readingReminderDays,
                                 base: base, title: title, body: body,
                                 action: "open-bible", center: center)
        }

        // Memory review reminder — 5 minutes later. Gated by BOTH memory toggles:
        // the Notification-settings "Memory Review Reminders" and the Memory-settings
        // "Daily Memory Reminders" describe the same notification, so turning off
        // either one silences it.
        if settings.memoryReviewReminders && settings.dailyMemoryReminders {
            scheduleWeekdaySlots(prefix: "review-reminder", days: settings.memoryReminderDays,
                                 base: Self.offset(base, byMinutes: 5),
                                 title: "Verse Review Time",
                                 body: "Strengthen your memory with a quick verse review.",
                                 action: "open-memory", center: center)
        }

        // Lesson reminder — 10 minutes later, on the same days as reading.
        if settings.lessonReminders {
            scheduleWeekdaySlots(prefix: "lesson-reminder", days: settings.readingReminderDays,
                                 base: Self.offset(base, byMinutes: 10),
                                 title: "Continue Your Lesson",
                                 body: "Pick up where you left off in your discipleship track.",
                                 action: "open-lessons", center: center)
        }

        // Weekly accountability-report reminder — its own day/time, independent of
        // the daily reminder slots. Only fires once a partner actually exists.
        scheduleWeeklyPartnerReportReminder(center: center)
    }

    /// Weekly nudge to send the accountability report. Opt-in (defaults off) and
    /// scheduled here so `scheduleDailyReminder()` stays the single source of
    /// truth — it removes `partner-report-reminder` before every rebuild, so this
    /// can never stack.
    @MainActor private func scheduleWeeklyPartnerReportReminder(center: UNUserNotificationCenter) {
        let partner = AccountabilityPartnerService.shared
        guard partner.reminderEnabled, partner.hasPartner else { return }

        let time = Calendar.current.dateComponents([.hour, .minute], from: partner.reminderTime)
        var trigger = DateComponents()
        trigger.weekday = partner.reminderDay
        trigger.hour = time.hour
        trigger.minute = time.minute

        let content = UNMutableNotificationContent()
        content.title = "Send your accountability report"
        content.body = "Take a minute to send \(partner.partnerName) this week's shield report."
        content.sound = .default
        content.userInfo = ["action": "open-accountability"]

        let request = UNNotificationRequest(
            identifier: "partner-report-reminder",
            content: content,
            trigger: UNCalendarNotificationTrigger(dateMatching: trigger, repeats: true)
        )
        center.add(request, withCompletionHandler: nil)
    }

    // MARK: - Personalized Daily Reading Notifications (Gemini)

    /// Generates personalized reading-reminder copy via Gemini (at most once per day),
    /// caches it, then rebuilds the daily reminders so today's reading slot uses it.
    @MainActor func schedulePersonalizedReadingReminders() {
        let settings = SettingsManager.shared
        guard settings.notificationsEnabled, settings.readingPlanReminders, settings.aiEnabled else { return }

        // Throttle: only generate once per calendar day.
        let defaults = UserDefaults.standard
        if let last = defaults.object(forKey: personalizedLastDateKey) as? Date,
           Calendar.current.isDateInToday(last) { return }

        Task {
            let planContext = await Self.activePlanContext()
            do {
                let (title, body) = try await GeminiService.shared.generateDailyReadingNotification(
                    planName: planContext.planName,
                    todaysReading: planContext.todaysReading
                )
                defaults.set(title, forKey: personalizedTitleKey)
                defaults.set(body, forKey: personalizedBodyKey)
                defaults.set(Date(), forKey: personalizedLastDateKey)
                // Rebuild so the reading slot picks up the personalized content.
                scheduleDailyReminder()
            } catch {
                // Gemini unavailable — static reminders from scheduleDailyReminder() remain.
                debugLog("[NotificationManager] Gemini notification generation failed: \(error)")
            }
        }
    }

    /// Returns the name and today's reading reference for the user's most-progressed active plan.
    private static func activePlanContext() async -> (planName: String?, todaysReading: String?) {
        await MainActor.run {
            let service = ReadingPlanService.shared
            // Find the plan the user has made the most progress in
            let active = BibleReadingPlans.all.filter { service.hasStarted($0.id) }
            guard let plan = active.max(by: { service.currentDay(for: $0.id) < service.currentDay(for: $1.id) }) else {
                return (nil, nil)
            }
            let dayIndex = service.currentDay(for: plan.id) - 1
            guard dayIndex >= 0, dayIndex < plan.entries.count else {
                return (plan.name, nil)
            }
            let entry = plan.entries[dayIndex]
            return (plan.name, entry.isReflectionDay ? "a reflection day" : entry.scriptureReference)
        }
    }

    /// Schedule a local notification (for testing)
    @MainActor func schedulePodcastNotification(episodeCount: Int, title: String) {
        let settings = SettingsManager.shared
        guard settings.podcastNewEpisodeNotifications, settings.notificationsEnabled else { return }

        let content = UNMutableNotificationContent()
        content.title = episodeCount == 1 ? "New Walk Talks Episode" : "\(episodeCount) New Walk Talks Episodes"
        content.body = episodeCount == 1 ? title : "Open the Discipleship tab to listen."
        content.sound = .default

        let components = Calendar.current.dateComponents([.hour, .minute], from: settings.podcastNotificationTime)
        let now = Date()
        let trigger: UNNotificationTrigger
        if let fire = Calendar.current.nextDate(after: now, matching: components, matchingPolicy: .nextTime), fire > now {
            trigger = UNCalendarNotificationTrigger(dateMatching: components, repeats: false)
        } else {
            trigger = UNTimeIntervalNotificationTrigger(timeInterval: 60, repeats: false)
        }

        let request = UNNotificationRequest(
            identifier: "podcast-new-episode-\(Int(Date().timeIntervalSince1970))",
            content: content,
            trigger: trigger
        )
        UNUserNotificationCenter.current().add(request) { error in
            if let error = error {
                debugLog("Podcast notification error: \(error.localizedDescription)")
            }
        }
    }

    func scheduleLocalNotification(title: String, body: String, delay: TimeInterval = 5) {
        let content = UNMutableNotificationContent()
        content.title = title
        content.body = body
        content.sound = .default
        
        let trigger = UNTimeIntervalNotificationTrigger(timeInterval: delay, repeats: false)
        let request = UNNotificationRequest(identifier: UUID().uuidString, content: content, trigger: trigger)
        
        UNUserNotificationCenter.current().add(request) { error in
            if let error = error {
                debugLog("Error scheduling notification: \(error.localizedDescription)")
            }
        }
    }
    
    /// Clear all pending notifications
    func clearPendingNotifications() {
        UNUserNotificationCenter.current().removeAllPendingNotificationRequests()
    }
    
    /// Clear all delivered notifications
    func clearDeliveredNotifications() {
        UNUserNotificationCenter.current().removeAllDeliveredNotifications()
    }
    
    /// Reset badge count
    func resetBadgeCount() {
        DispatchQueue.main.async {
            UIApplication.shared.applicationIconBadgeNumber = 0
        }
    }

    // MARK: - Weekly Check-ins

    /// Schedule exactly ONE weekly check-in notification at the day and time the user
    /// has configured. A random check-in is picked from the provided list each time
    /// this method runs (i.e. each time the app refreshes from Supabase or the user
    /// changes their notification day/time).
    func scheduleWeeklyCheckins(_ checkins: [WeeklyCheckin]) async {
        let center = UNUserNotificationCenter.current()
        // Remove the single weekly check-in slot before rescheduling.
        center.removePendingNotificationRequests(withIdentifiers: ["checkin-weekly"])

        guard !checkins.isEmpty else { return }

        // Read user preferences on the main actor.
        let (enabled, weekday, hour, minute) = await MainActor.run {
            let s = SettingsManager.shared
            let comps = Calendar.current.dateComponents([.hour, .minute], from: s.weeklyCheckinTime)
            return (
                s.weeklyCheckinEnabled && s.notificationsEnabled,
                s.weeklyCheckinDay,
                comps.hour ?? 9,
                comps.minute ?? 0
            )
        }
        guard enabled else { return }

        // Pick a random check-in from the full list.
        guard let checkin = checkins.randomElement() else { return }

        var dateComponents = DateComponents()
        dateComponents.weekday = weekday
        dateComponents.hour = hour
        dateComponents.minute = minute

        let content = UNMutableNotificationContent()
        content.title = checkin.title
        content.body = checkin.message
        content.sound = .default

        let trigger = UNCalendarNotificationTrigger(dateMatching: dateComponents, repeats: true)
        let req = UNNotificationRequest(identifier: "checkin-weekly", content: content, trigger: trigger)
        try? await center.add(req)
    }
}
