create table if not exists public.ai_request_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid null,
  identity_key text not null,
  operation text not null,
  cache_key text null,
  prompt_chars integer not null default 0,
  status_code integer not null,
  duration_ms integer not null default 0,
  error_message text null
);

create index if not exists ai_request_logs_identity_created_at_idx
  on public.ai_request_logs (identity_key, created_at desc);

create index if not exists ai_request_logs_user_created_at_idx
  on public.ai_request_logs (user_id, created_at desc);

create table if not exists public.ai_response_cache (
  cache_key text primary key,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  operation text not null,
  response_text text not null
);

create index if not exists ai_response_cache_expires_at_idx
  on public.ai_response_cache (expires_at);

alter table public.ai_request_logs enable row level security;
alter table public.ai_response_cache enable row level security;
